DROP TABLE "test".dbo.volunteer_period
DROP TABLE "test".dbo.feedback
DROP TABLE "test".dbo.volunteer
DROP TABLE "test".dbo.event
DROP TABLE "test".dbo.app_user
DROP TABLE "test".dbo.user_type
DROP TABLE "test".dbo.address
DROP TABLE "test".dbo.emergency_contact
DROP TABLE "test".dbo.job_type
DROP TABLE "test".dbo.location